### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by CHZarles** [tianqiaotiemo/complier#3]
![image](https://user-images.githubusercontent.com/51184391/113991462-0eb8da80-9885-11eb-8e24-115beca0a41e.png)

![image](https://user-images.githubusercontent.com/51184391/113991360-f47efc80-9884-11eb-9a37-9742c111360d.png)
你好，我在复现你的实验的时候，卡在这个函数里面了。
没有解决思路

**Comment by CHZarles** [comment]
找到解决方法了
TAC.C文件中对应的地方做如下修改(在声明数组的时候加上static )
![image](https://user-images.githubusercontent.com/51184391/114139307-76346000-9941-11eb-9ba9-9b00e53adeee.png)
![image](https://user-images.githubusercontent.com/51184391/114139681-ecd15d80-9941-11eb-93b2-3093f6fef677.png)
![image](https://user-images.githubusercontent.com/51184391/114139695-f0fd7b00-9941-11eb-8fa8-d5c349bc063d.png)
![image](https://user-images.githubusercontent.com/51184391/114139713-f65ac580-9941-11eb-9e26-e013859e3464.png)
![image](https://user-images.githubusercontent.com/51184391/114139743-007cc400-9942-11eb-96b5-158fb0702664.png)

**Comment by lili365** [comment]
这个怎么运行的呀，用的什么工具

**Comment by lili365** [comment]
我用devc++运行不了
